### ISSUE TITLE
Retry when an AMI name is taken

### ISSUE THREAD

**Issue by igalarzab** [ticketea/forseti#14]
When an AMI name is taken forseti fails creating a new one. It should retry with the following numbers until it find one that is not used.

```

Traceback (most recent call last): . 0:00:00
  File "/home/ubuntu/.virtualenvs/forseti/bin/forseti", line 9, in <module>
    load_entry_point('forseti==0.1.2', 'console_scripts', 'forseti')()
  File "/home/ubuntu/.virtualenvs/forseti/local/lib/python2.7/site-packages/forseti-0.1.2-py2.7.egg/forseti/cli.py", line 87, in main
    forseti_command.run(configuration, arguments)
  File "/home/ubuntu/.virtualenvs/forseti/local/lib/python2.7/site-packages/forseti-0.1.2-py2.7.egg/forseti/commands/commands.py", line 72, in run
    deployer.deploy(cli_arguments['--ami'])
  File "/home/ubuntu/.virtualenvs/forseti/local/lib/python2.7/site-packages/forseti-0.1.2-py2.7.egg/forseti/deployers/deploy_and_snapshot.py", line 123, in deploy
    ami_id = self.generate_ami()
  File "/home/ubuntu/.virtualenvs/forseti/local/lib/python2.7/site-packages/forseti-0.1.2-py2.7.egg/forseti/deployers/deploy_and_snapshot.py", line 157, in generate_ami
    raise exception
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidAMIName.Duplicate</Code><Message>AMI name afrodita-ami-2015-07-17-3 is already in use by AMI ami-c6f4bab1</Message></Error></Errors><RequestID>48b07635-d744-48f2-817e-a68701b413a0</RequestID></Response>
```

**Comment by igalarzab** [comment]
:+1:
